In [30]:
import sys
sys.path.insert(0,'../code/')
import Top
import numpy as np
import random
random.seed(12345)
np.random.seed(12345)

n = 1500
p = 1000
N = 1500
K = 30
Xi = 1/p
Ik_card = int(p/100)


## generate W
W = np.zeros(shape = [K,n])
for c in range(n):
    S = np.random.randint(1,np.floor(K/3),1)[0]    
    entry = np.random.uniform(0,1,S)
    entry_indx = random.sample(range(K),k = S)
    for en,ind in zip(entry,entry_indx):
        W[ind,c] = en
    W[:,c] = W[:,c]/W[:,c].sum()
    


## get I and its partition
voc_indx = [x for x in range(p)]
random.shuffle(voc_indx)
voc_anchor = voc_indx[:K*Ik_card]
voc_nonanchor = voc_indx[K*Ik_card+1:]

voc_anchor = np.asarray(voc_anchor).reshape(Ik_card,K)

## generate A
A = np.zeros(shape=[p,K])
for k in range(K):
    A[voc_anchor[:,k],k] = [K*Xi]*Ik_card
    A[voc_nonanchor,k] = np.random.uniform(0,1,len(voc_nonanchor))
    A[voc_nonanchor,k] /= A[voc_nonanchor,k].sum()
    A[voc_nonanchor,k] *= 1-sum(A[voc_indx[:K*Ik_card],k])
    #A[voc_nonanchor,k] *= 1-sum(A[voc_anchor[:,k],k])
    A[voc_nonanchor,k]*A[voc_nonanchor,k].sum()/(1-sum(A[voc_indx[:K*Ik_card],k]))

AW = np.dot(A,W)

## generate X
X = np.zeros(shape = [p,n])
for column in range(n):
    X[:,column] = np.random.multinomial(N,AW[:,column])




In [31]:
np.where(X.sum(axis = 1) == 0)

(array([902]),)

In [49]:
import time
start = time.time()
test = Top.Top(X)
print("run finished after " + str(time.time() - start))

run finished after 3.654646635055542


## evaluate result

## K

In [50]:
print(test["K"])

30


### Comment:
K is right

### Anchor word

In [47]:
## 
anchor_out = []
out = np.sort(test["Anchor words"])
for i in range(len(test["Anchor words"])):
    if out[i] < 902:
        anchor_out.append(out[i])
    else:
        anchor_out.append(out[i]+1)
    
#np.sort(test["Anchor words"])
#np.sort(anchor_out)
#np.sort(voc_indx[:K*Ik_card])

In [48]:
np.sort(anchor_out) == np.sort(voc_indx[:K*Ik_card])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

## Comment: 
I have changed the X in the input (by taking out the rows that have zero sums) (actually only row 902). So after adjusting for that in fact, the anchor words are exactly the same.

## Anchor groups (not finished yet)

In [51]:
test["Anchor groups"]

[[676, 357, 836, 711, 8, 393, 296, 599, 922, 861],
 [961, 133, 299, 75, 12, 397, 559, 465, 694, 154],
 [320, 416, 163, 553, 781, 206, 245, 24, 636, 478],
 [131, 453, 165, 741, 968, 973, 815, 879, 471, 27],
 [611, 746, 235, 303, 146, 341, 917, 472, 251, 30],
 [32, 578, 327, 331, 492, 846, 336, 337, 369, 543],
 [960, 579, 484, 742, 39, 363, 589, 339, 500, 152],
 [837, 107, 43, 459, 462, 816, 306, 884, 405, 954],
 [608, 642, 261, 615, 491, 155, 47, 948, 91, 446],
 [193, 98, 871, 841, 426, 779, 78, 175, 48, 431],
 [388, 805, 555, 428, 845, 686, 496, 50, 567, 475],
 [577, 772, 74, 204, 110, 307, 85, 55, 313, 255],
 [739, 934, 103, 587, 366, 623, 792, 793, 59, 732],
 [425, 108, 334, 368, 433, 976, 184, 378, 188, 62],
 [678, 717, 207, 81, 497, 342, 729, 667, 574, 863],
 [289, 457, 844, 941, 82, 819, 344, 986, 286, 479],
 [96, 516, 868, 401, 595, 533, 311, 600, 249, 699],
 [576, 864, 102, 936, 490, 271, 338, 695, 312, 250],
 [774, 263, 104, 649, 395, 939, 240, 278, 795, 445],
 [705, 834, 929, 

In [52]:
voc_anchor

array([[484, 708, 220, 679, 781, 642, 204, 967, 618, 869, 942, 863, 940,
        236, 428, 856, 312, 808,  30, 779, 543, 191, 108, 533, 165, 962,
        955, 923, 892, 793],
       [961, 365, 811, 668, 163, 491, 313, 486, 464, 280, 479,  81, 774,
        763, 567, 488, 250, 540, 251,  48, 331, 513, 977, 401, 974, 465,
         43, 861, 907, 366],
       [500, 887, 976, 470,  24, 949, 577, 160, 452, 417, 344, 574, 395,
        992, 805, 827, 864, 273, 746,  98, 336, 706, 425, 249,  27, 133,
        837,   8, 370, 103],
       [339, 956, 858, 130, 206,  47, 110, 890, 315, 716, 289, 678, 104,
        117, 845, 705, 576, 126, 303, 175, 846, 947, 368, 595, 131, 154,
        306, 296, 449, 935],
       [363, 178, 639, 853, 245,  91,  55, 266, 229, 838,  82, 717, 445,
        149,  50, 834, 695, 267, 611, 193, 492, 820, 184, 311, 879, 299,
        884, 676, 483, 623],
       [579, 494, 161, 145, 320, 608, 772, 727, 523, 826, 286, 729, 278,
        348, 555, 487, 937, 796, 235,  78, 578, 518,

## Try on real data